name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NEXT_TELEMETRY_DISABLED: '1'
      CI: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Unit tests (Vitest + coverage)
        run: npx vitest run --coverage

      - name: Upload coverage (lcov)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-lcov
          path: coverage/lcov.info
          if-no-files-found: ignore

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: E2E tests (Playwright)
        run: npx playwright test --reporter=line

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report
